import scrapy

class CompanyItem(scrapy.Item):
    name             = scrapy.Field()
    category         = scrapy.Field()
    sub_category     = scrapy.Field()
    description      = scrapy.Field()
    phone            = scrapy.Field()
    phone_whatsapp   = scrapy.Field()
    email            = scrapy.Field()
    website          = scrapy.Field()
    address          = scrapy.Field()
    city             = scrapy.Field()
    region           = scrapy.Field()
    country          = scrapy.Field()
    latitude         = scrapy.Field()
    longitude        = scrapy.Field()
    source           = scrapy.Field()
    source_url       = scrapy.Field()
    google_place_id  = scrapy.Field()
    facebook_page_id = scrapy.Field()
    rating           = scrapy.Field()
    reviews_count    = scrapy.Field()
    job_id           = scrapy.Field()
    tags             = scrapy.Field()
    scrape_query     = scrapy.Field()
